Repository mucinoab/Reporstat, pull requests merged in 2021-02, with the labels that each got.

#70 Indicadores de pobreza CONEVAL
  .gitignore
  Manifest.toml
  docs/src/index.md
  src/Utils.jl
Labels: documentation, enhancement

#76 Agrega extensión territorial.
  .gitignore
  src/Inegi.jl
  src/Utilidades.jl
  test/utils.jl
Labels: bug, documentation, enhancement

#81 Códigos postales
  .gitignore
  docs/src/index.md
  src/Inegi.jl
  src/Utilidades.jl
Labels: bug, enhancement

#89 Agrega funciones de similitud de strings.
  Manifest.toml
  Project.toml
  docs/src/index.md
  src/Inegi.jl
Labels: documentation, enhancement

#92 Arregla documentación e indentación general.
  docs/make.jl
  docs/src/index.md
  src/Inegi.jl
  src/Stats.jl
  src/Utilidades.jl
  test/runtests.jl
Labels: documentation

#94 Corrijo errores
  docs/src/index.md
  src/Inegi.jl
Labels: bug, documentation, enhancement

#97 Cambia nombre de constantes a mayúsculas.
  src/Constants.jl
  src/Inegi.jl
Labels: documentation

#98 Correción de errores ortográficos
  .github/workflows/Documentation.yml
  .gitignore
  LICENSE
  README.md
  docs/src/index.md
  src/Inegi.jl
  src/Stats.jl
  src/Utilidades.jl
Labels: documentation

#103 Actualiza dependencias y agrega ZipFile
  Manifest.toml
  Project.toml
Labels: enhancement
